AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*.rb'
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
  TargetRubyVersion: 2.3

Style/EndOfLine:
  EnforcedStyle: lf

Naming/UncommunicativeMethodParamName:
  AllowedNames: [_, x, y, z, i, io, id]
