sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.0
  - 2.4
  - 2.5
  - 2.6
  - rbx-3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: 2.6
before_install:
  - gem update --system
  - gem --version
install:
  - bundle install --with development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
